export const ADD_PLAYER_REQUEST = 'ADD_PLAYER_REQUEST';
export const ADD_PLAYER_SUCCESS = 'ADD_PLAYER_SUCCESS';
export const ADD_PLAYER_FAIL = 'ADD_PLAYER_FAIL';

export const PLAYER_LIST_REQUEST = 'PLAYER_LIST_REQUEST';
export const PLAYER_LIST_SUCCESS = 'PLAYER_LIST_SUCCESS';
export const PLAYER_LIST_FAIL = 'PLAYER_LIST_FAIL';

export const DELETE_PLAYER_REQUEST = 'DELETE_PLAYER_REQUEST';
export const DELETE_PLAYER_SUCCESS = 'DELETE_PLAYER_SUCCESS';
export const DELETE_PLAYER_FAIL = 'DELETE_PLAYER_FAIL';

export const ADD_SCORE_SUCCESS = 'ADD_SCORE_SUCCESS';

export const SUB_SCORE_SUCCESS = 'SUB_SCORE_SUCCESS';

export const SCORE_RESET = 'SCORE_RESET';

export const ADD_CHAMP_REQUEST = 'ADD_CHAMP_REQUEST';
export const ADD_CHAMP_SUCCESS = 'ADD_CHAMP_SUCCESS';
export const ADD_CHAMP_FAIL = 'ADD_CHAMP_FAIL';

export const SUB_CHAMP_REQUEST = 'SUB_CHAMP_REQUEST';
export const SUB_CHAMP_SUCCESS = 'SUB_CHAMP_SUCCESS';
export const SUB_CHAMP_FAIL = 'SUB_CHAMP_FAIL';

export const ADD_WIN = 'ADD_WIN';
export const SUB_WIN = 'SUB_WIN';
